// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5lZeqanID_6SCS7YmIn4lrHUT57cKXDo',
    appId: '1:138153895418:web:20e269a33af31000547043',
    messagingSenderId: '138153895418',
    projectId: 'meowpic-bbfb0',
    authDomain: 'meowpic-bbfb0.firebaseapp.com',
    storageBucket: 'meowpic-bbfb0.appspot.com',
    measurementId: 'G-RSB01JTCF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAowHv-dNLVWlCWoxzq2TNiURovk08x54I',
    appId: '1:138153895418:android:4da384332bf16ea8547043',
    messagingSenderId: '138153895418',
    projectId: 'meowpic-bbfb0',
    storageBucket: 'meowpic-bbfb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwLplcQ0ePNsbW2biiZ7YApwbArT6GXg',
    appId: '1:138153895418:ios:ae25244859c86577547043',
    messagingSenderId: '138153895418',
    projectId: 'meowpic-bbfb0',
    storageBucket: 'meowpic-bbfb0.appspot.com',
    iosClientId: '138153895418-phiiadu4t4phpc7mtakl0e4ku3rgt1mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwLplcQ0ePNsbW2biiZ7YApwbArT6GXg',
    appId: '1:138153895418:ios:ae25244859c86577547043',
    messagingSenderId: '138153895418',
    projectId: 'meowpic-bbfb0',
    storageBucket: 'meowpic-bbfb0.appspot.com',
    iosClientId: '138153895418-phiiadu4t4phpc7mtakl0e4ku3rgt1mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
